---
- name: Add global_parameters
  theforeman.foreman.global_parameter:
    server_url: "{{ foreman_server_url | default(omit) }}"
    username: "{{ foreman_username | default(omit) }}"
    password: "{{ foreman_password | default(omit) }}"
    validate_certs: "{{ foreman_validate_certs | default(omit) }}"
    name: "{{ foreman_global_parameters_item.name }}"
    updated_name: "{{ foreman_global_parameters_item.updated_name | default(omit) }}"
    value: "{{ foreman_global_parameters_item.value | default(omit) }}"
    hidden_value: "{{ foreman_global_parameters_item.hidden_value | default(omit) }}"
    parameter_type: "{{ foreman_global_parameters_item.parameter_type | default(omit) }}"
    state: "{{ foreman_global_parameters_item.state | default(omit) }}"
  loop: "{{ foreman_global_parameters | default([]) }}"
  loop_control:
    loop_var: foreman_global_parameters_item
