name: Lint and Test

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/test-ansible-collection.yaml@main
    with:
      targets: |
       roles/architectures
       roles/installation_mediums
       roles/job_templates
       roles/locations
       roles/roles
